### ISSUE TITLE
Active Users Gauge shows Negative Value

### ISSUE THREAD

**Issue by kamrajshahapure** [AndreyVMarkelov/prom-bitbucket-exporter#14]
Hi,

First of all, thanks for the plugin development, it has helped a lot.

I am facing a strange issue. On my Prometheus endpoint I am having a wrong metric for active users guage, here is a screenshot.

![image](https://user-images.githubusercontent.com/33791474/46393662-c3497280-c703-11e8-8c4a-5b7355d8fb17.png)

# HELP bitbucket_active_users_gauge Active Users Gauge
# TYPE bitbucket_active_users_gauge gauge
bitbucket_active_users_gauge -1.0

for test purpose I have only 2 users right now and both are logged in.

Bitbucket version 5.14.1 and latest jar plugin for Bitbucket from Atlassian marketplace.

**Comment by AndreyVMarkelov** [comment]
I see. Wjll fix today

ср, 3 окт. 2018 г., 9:53 kamrajshahapure <notifications@github.com>:

**Comment by kamrajshahapure** [comment]
@AndreyVMarkelov Thanks, looking forward to it

**Comment by kamrajshahapure** [comment]
@AndreyVMarkelov Thank you very much for the fix, BTW did you upload the jar on the atlassian Marketplace?
because I may not be able to compile this project, importing the jar from marketplace will be a better option.

**Comment by AndreyVMarkelov** [comment]
Did, but only server. Dc will be in 1 2 weeks. Atlassian complicates this
stuff. I need help with dc

чт, 4 окт. 2018 г., 13:00 kamrajshahapure <notifications@github.com>:
