### ISSUE TITLE
process_start_time_seconds always shows same value

### ISSUE THREAD

**Issue by Trivikramreddy** [AndreyVMarkelov/prom-bitbucket-exporter#15]
process_start_time_seconds metric doesn't show the accurate time. In my case it is always constant.
![screen shot 2018-10-04 at 2 02 13 pm](https://user-images.githubusercontent.com/25829092/46499760-2c051d80-c7de-11e8-974d-3fa8f8acb56c.png)

**Comment by AndreyVMarkelov** [comment]
Hi. What is should be? It is the time when jvm started

**Comment by Trivikramreddy** [comment]
Yes, you are right but it shows the same time today and tomorrow. It never changes the process_start_time is always 1.535029428526E9
