### ISSUE TITLE
Add metric for maximum allowed users

### ISSUE THREAD

**Issue by chrisipa** [AndreyVMarkelov/prom-bitbucket-exporter#19]
Hi @AndreyVMarkelov ,

thanks for your great work on this Prometheus Bitbucket exporter. Could you please also add this metric here?

`bitbucket_allowed_users_gauge`

This metric is pretty important for us to send alarms if we only have a few bitbucket licences left. Here's an example alert rule for Prometheus which would notify us in case of 80% of the licences used:

`bitbucket_active_users_gauge / bitbucket_allowed_users_gauge * 100 > 80`

You already have comparable metrics for your JIRA and Confluence exporters.

Thank you very much.

Best regards
Chris

**Comment by AndreyVMarkelov** [comment]
Done

**Comment by chrisipa** [comment]
Wow that was really quick. I have tested the new release and everything works as expected. Great job.
