### ISSUE TITLE
missing bitbucket metrics

### ISSUE THREAD

**Issue by kbudde** [AndreyVMarkelov/prom-bitbucket-exporter#3]
Hi,

I've just installed the exporter.
Calling the metrics endpoint from browser is working as long as I'm logged in to bitbucket.
If I try the same while I'm logged out only jvm and process metrics are exported.
I've tried as well with token.

Prometheus is not authenticated so some important metrics are missing.

Bitbucket version: 5.6.2

**Comment by oneohtrix** [comment]
I've got the same issue, Prometheus doesn't recognize the Bitbucket metrics.

**Comment by AndreyVMarkelov** [comment]
Hi. Will fix asap. Does it work if open manually right?

20 Фев 2018 г. 23:46 пользователь "[Redacted]" <notifications@github.com>
написал:

**Comment by kbudde** [comment]
Hi,

yes it is working while I'm logged in to bitbucket.

**Comment by AndreyVMarkelov** [comment]
Done. @kbudde Thank you for letting me know. Please, share another ideas in tickets.
Actually there are plan to build some fancy repo metrics line codes etc. But it will be sceduled processes means with some delay 1 minute f.e.

**Comment by kbudde** [comment]
HI,

new version is working as exepcted.
