### ISSUE TITLE
version 4.6.1 support

### ISSUE THREAD

**Issue by aviorma** [AndreyVMarkelov/prom-bitbucket-exporter#9]
hello

i would like this exporter to support version 4.6.1
is that possible ?

i already tried to install the add-on and when i tried to reach the endpoint /plugins/servlet/prometheus/metrics and i got 404 message: Could not find servlet for /plugins/servlet/prometheus/metrics

Thanks

**Comment by AndreyVMarkelov** [comment]
Done
